### ISSUE TITLE
Question about callbacks

### ISSUE THREAD

**Issue by lesliev** [pat/ts-delayed-delta#54]
Hi!

In this article about upgrading Thinking Sphinx:
https://freelancing-gods.com/thinking-sphinx/v5/upgrading.html

...it says I need to add an indexing callback like this to my indexed models:

```
  ThinkingSphinx::Callbacks.append(
    self, :behaviours => [:sql, :deltas]
  )
```

Is this still needed if I'm using `ts-delayed-delta`? My indexes don't seem to be updating when I add new records.

I'm busy upgrading a project from Thinking Sphinx 4.0 to 5.4 and I'm not too familiar with Sphinx.

**Comment by pat** [comment]
Yup, you'll still need the callbacks, and to include both of those behaviours (`:sql` and `:deltas`). When you've added that in, are you finding it's still not working?

**Comment by lesliev** [comment]
Adding those callbacks does solve the problem. Does this mean I can remove `ts-delayed-delta`, or do the callbacks and `ts-delayed-delta` do different things?

**Comment by pat** [comment]
You'll need to keep the gem - the callbacks tell TS to fire off the delta logic, but it's in the index definitions that specify which delta approach to use (the default is inline instead of via Delayed Job, hence the need for the gem).

**Comment by lesliev** [comment]
Awesome, thanks for the help!
